name: Build conda packages

on:
  push:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(vars.BUILD_OS)}}
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS)}}
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install Visual Studio Build Tools
        if: matrix.os == 'windows-latest' # Only run this on Windows
        run: |
          choco install visualstudio2019buildtools --version 16.11.7 --params "/NoRestart"
          choco install visualstudio2019-workload-vctools --params "/NoRestart"
      - uses: actions/checkout@v4
      - name: update submodules
        #       shell: bash -l {0}
        run: |
          git submodule update --init --recursive
      - name: Conda build
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN  }}
        shell: bash -l {0}
        run: |
          conda install -c conda-forge conda-build scikit-build-core numpy cython anaconda-client conda-libmamba-solver -y
          conda build -c conda-forge -c loop3d --output-folder conda conda  --python ${{matrix.python-version}}
          # conda convert -p all conda/linux-64/*.tar.bz2 -f -o conda
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: conda-build-${{ matrix.python-version }}-${{ matrix.os }}
          path: conda
